version: '3.9'

services:
  food-memo-db:
    image: mysql:8.0.33
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: food_memo
      MYSQL_USER: food_memo
      MYSQL_PASSWORD: food_memo
    restart: always
