spring:
  datasource:
    url: ${DB_JDBC_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:food_memo}
    password: ${DB_PASSWORD:food_memo}

  mvc:
    hiddenmethod:
      filter:
        enabled: true

aws:
  credential:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  s3:
    region: ${AWS_S3_REGION}
    bucketName: ${AWS_S3_BUCKET_NAME}
