spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_memo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: food_memo
    password: food_memo

  mvc:
    hiddenmethod:
      filter:
        enabled: true

aws:
  credential:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  s3:
    region: ${AWS_S3_REGION}
    bucketName: ${AWS_S3_BUCKET_NAME}
